# **PyTorch:**

1. PyTorch is an open-source machine learning library developed by Facebook.

2. It is widely used for various machine learning tasks, including deep learning.

3. PyTorch provides a flexible and dynamic computational graph, making it popular among researchers and practitioners. It supports dynamic computation, which allows for easy debugging and experimentation.

In [ ]:
!pip install torch torchvision

In [ ]:
import torch
import torchvision

# **Tensors:**
1. Tensors are the fundamental data structures in PyTorch.

2. They are similar to NumPy arrays but come with additional features, especially for deep learning.

3. Tensors can represent scalars, vectors, matrices, or higher-dimensional arrays.

4. PyTorch tensors can be manipulated and operated on using a wide range of functions, and they can also track gradients for automatic differentiation.

In [ ]:
## 3. Tensors
# Creating tensors
tensor_a = torch.tensor([1, 2, 3])
tensor_b = torch.tensor([[4, 5, 6], [7, 8, 9]])

In [ ]:
# Operations on tensors
tensor_sum = tensor_a + tensor_b
tensor_sum

tensor([[ 5,  7,  9],
        [ 8, 10, 12]])

In [ ]:
tensor_multiply = tensor_a * tensor_b
tensor_multiply

tensor([[ 4, 10, 18],
        [ 7, 16, 27]])

# **Autograd (Automatic Differentiation):**
1. Autograd, short for automatic differentiation, is a key feature in PyTorch.

2. It allows the system to automatically calculate gradients of tensors with respect to some variable.

3. This is crucial for training neural networks using gradient-based optimization algorithms.

4. When you set requires_grad=True for a PyTorch tensor, it starts to track operations on it, and you can later perform a backward pass to compute gradients.



In [ ]:
## 4. Autograd
# Tensors with gradient tracking
tensor_with_grad = torch.tensor([1.0, 2.0, 3.0], requires_grad=True)
output = 3 * (tensor_with_grad ** 2).sum()

In [ ]:
# Print the output
print("Output:", output.item())

Output: 42.0


In [ ]:
# Backward pass to compute gradients
output.backward()

In [ ]:
# Accessing gradients
gradients = tensor_with_grad.grad

In [ ]:
# Print the gradients
print("Gradients:", gradients)

Gradients: tensor([ 6., 12., 18.])


# **Neural Networks:**
1. Neural networks form the backbone of deep learning.

2. In PyTorch, you can define and train neural networks using the torch.nn module. This module provides classes and functions for building various types of neural network architectures, such as fully connected networks, convolutional networks, and recurrent networks.

3. It includes predefined layers, loss functions, and optimization algorithms to facilitate the construction and training of neural networks.

In [ ]:
## 5. Neural Networks
import torch.nn as nn


In [ ]:
# Define a simple neural network
class SimpleNN(nn.Module):
    def __init__(self):
        super(SimpleNN, self).__init__()
        self.fc = nn.Linear(10, 5)

    def forward(self, x):
        return self.fc(x)

In [ ]:
# Instantiate the network
simple_model = SimpleNN()


In [ ]:
## 6. Loss and Optimization
# Define a loss function
criterion = nn.MSELoss()

# Define an optimizer
optimizer = torch.optim.SGD(simple_model.parameters(), lr=0.01)


In [ ]:
## 7. Training Loop
# Sample data for training
input_data = torch.randn((100, 10))
target_data = torch.randn((100, 5))

# Training loop
for epoch in range(100):
    # Forward pass
    output_data = simple_model(input_data)

    # Compute loss
    loss = criterion(output_data, target_data)

    # Backward pass and optimization
    optimizer.zero_grad()
    loss.backward()
    optimizer.step()

This code generates random input data for validation, passes it through the trained model, and prints the resulting output. The actual output values will depend on the weights learned during the training process and the specific data used for validation.







In [ ]:
# Evaluation on a validation set
validation_input = torch.randn((10, 10))
validation_output = simple_model(validation_input)

print("Validation Output:")
print(validation_output)

Validation Output:
tensor([[ 0.0653, -0.1343, -0.1077, -0.5262,  0.2214],
        [ 0.3202, -0.4175, -0.4803,  0.3323, -0.3410],
        [ 0.1164,  0.4438,  1.0149,  0.2379, -0.2639],
        [-0.2537, -0.2586,  0.4478,  0.0846, -0.4499],
        [ 0.4264,  0.9571, -0.5702, -0.9395,  0.7159],
        [-0.2000,  0.1830, -0.7054, -0.5051,  0.5223],
        [-0.6934, -0.7542, -0.3835, -0.5341,  0.4562],
        [ 0.7265,  0.3655,  0.1854,  0.0740,  0.1627],
        [ 0.0363, -0.0160, -0.5201, -0.0821,  0.2671],
        [ 0.6184,  0.2926, -0.4838, -0.0382,  0.6380]],
       grad_fn=<AddmmBackward0>)
