## Import the __`torch`__ package

In [ ]:
import torch as pt
pt.manual_seed(0);

## Create a vector of ten zeros

In [ ]:
v = pt.zeros(10).reshape(5, 2)
v

tensor([[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]])

## Create a vector of size ten with nine zeros and a 1 in the fifth position

In [ ]:
v = pt.zeros(10)
v[4] = 1
v

tensor([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

## Create a vector with values ranging from 10 to 49

In [ ]:
v = pt.arange(10, 50)
v

tensor([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27,
        28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45,
        46, 47, 48, 49])

## Reverse the previous vector

In [ ]:
reversed(v)

tensor([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33, 32,
        31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16, 15, 14,
        13, 12, 11, 10])

## Create a 3x3 matrix with values ranging from 0 to 8

In [ ]:
m = pt.arange(0, 9).reshape(3, 3)
m

tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])

## Find the indices of the non-zero elements of the following array:

In [ ]:
v = pt.tensor([1, 2, 0, 0, 4, 0]) # Given
v

tensor([1, 2, 0, 0, 4, 0])

In [ ]:
pt.nonzero(v)

tensor([[0],
        [1],
        [4]])

In [ ]:
v[pt.nonzero(v)]

tensor([[1],
        [2],
        [4]])

## Create a 5x5 identity matrix

In [ ]:
m = pt.eye(5)
m

tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])

## Create a 3x3x3 array with random values

In [ ]:
a = pt.rand(3, 3, 3)
a

tensor([[[0.4963, 0.7682, 0.0885],
         [0.1320, 0.3074, 0.6341],
         [0.4901, 0.8964, 0.4556]],

        [[0.6323, 0.3489, 0.4017],
         [0.0223, 0.1689, 0.2939],
         [0.5185, 0.6977, 0.8000]],

        [[0.1610, 0.2823, 0.6816],
         [0.9152, 0.3971, 0.8742],
         [0.4194, 0.5529, 0.9527]]])

## Find the minimum and maximum values generated in the previous step

In [ ]:
a.min().item(), a.max().item()

(0.022325754165649414, 0.9527381062507629)

## Create a vector with 30 random values and find its mean

In [ ]:
v = pt.rand(30)
v.mean().item()

0.4639257490634918

## Create a 5x5 2d array with 1s around the edges and 0s in the middle

In [ ]:
a = pt.ones(5, 5)
a[1:-1, 1:-1] = 0
a

tensor([[1., 1., 1., 1., 1.],
        [1., 0., 0., 0., 1.],
        [1., 0., 0., 0., 1.],
        [1., 0., 0., 0., 1.],
        [1., 1., 1., 1., 1.]])

## Try to predict the output of each of the following cells before running them

In [ ]:
0 * float('nan')

nan

In [ ]:
float('nan') == float('nan')

False

In [ ]:
float('inf') > float('nan')

False

In [ ]:
float('nan') - float('nan')

nan

In [ ]:
0.3 == 3 * 0.1

False

In [ ]:
pt.tensor([0]) // pt.tensor([0]) #crashes the kernel :) continue with the next cell

In [ ]:
import torch as pt #this is in case you crashed on the previous cell
pt.tensor([0]) // pt.tensor([0.0])

tensor([nan])

In [ ]:
nan_scalar = pt.tensor([float('nan')])

pt.isnan(nan_scalar)

tensor([True])

In [ ]:
pt.tensor([0]) / pt.tensor([0.0])

tensor([nan])

## Find the integer part of the following array using four different methods:

In [ ]:
a = pt.randn((10,), dtype = pt.float32)
a

tensor([ 1.8740, -1.3836, -0.5305, -0.4313, -2.2858,  0.0700,  0.6674, -1.0403,
        -0.4820,  1.1293])

In [ ]:
a.to(dtype = pt.int8)

tensor([ 1, -1,  0,  0, -2,  0,  0, -1,  0,  1], dtype=torch.int8)

In [ ]:
pt.floor(a)

tensor([ 1., -2., -1., -1., -3.,  0.,  0., -2., -1.,  1.])

In [ ]:
pt.ceil(a) - 1

tensor([ 1., -2., -1., -1., -3.,  0.,  0., -2., -1.,  1.])

In [ ]:
pt.trunc(a)

tensor([ 1., -1., -0., -0., -2.,  0.,  0., -1., -0.,  1.])

## Create a vector of 10 values from 0 to 1, both included

In [ ]:
v = pt.linspace(0, 1, 10)
v

tensor([0.0000, 0.1111, 0.2222, 0.3333, 0.4444, 0.5556, 0.6667, 0.7778, 0.8889,
        1.0000])

## Create a vector of size 10 with values ranging from 0 to 1, both excluded

In [ ]:
v = pt.linspace(0, 1, 12)[1:-1]
v

tensor([0.0909, 0.1818, 0.2727, 0.3636, 0.4545, 0.5455, 0.6364, 0.7273, 0.8182,
        0.9091])

## Subtract the mean of each row of the following matrix

In [ ]:
m = pt.rand(3, 3)
m

tensor([[0.0652, 0.5460, 0.1872],
        [0.0340, 0.9442, 0.8802],
        [0.0012, 0.5936, 0.4158]])

In [ ]:
m[0, :]

tensor([0.0652, 0.5460, 0.1872])

In [ ]:
[pt.mean(m[i,:]) for i in pt.arange(0, 3)]

[tensor(0.2661), tensor(0.6195), tensor(0.3369)]

In [ ]:
pt.mean(m, 1, keepdim = False),

(tensor([0.2661, 0.6195, 0.3369]),)

In [ ]:
pt.mean(m, 1, keepdim = True),

(tensor([[0.2661],
         [0.6195],
         [0.3369]]),)

## Add 1,000,000 numbers together using __`torch`__ vectorized operations

In [ ]:
v = pt.rand((1_000_000))
%timeit pt.sum(v)

122 µs ± 11.5 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)


## Create a 4x4 array of the first 16 powers of 3

In [ ]:
a = pt.arange(16).reshape((4, 4))
3 ** a

tensor([[       1,        3,        9,       27],
        [      81,      243,      729,     2187],
        [    6561,    19683,    59049,   177147],
        [  531441,  1594323,  4782969, 14348907]])